### ISSUE TITLE
0.1 Client Closes

### ISSUE THREAD

**Issue by treboR-0** [ragemultiplayer/issues-archived#112]
======================
RageMP Client Closures - Because stability of the client is the second most important thing there is. Server Stability is number 1, to date, no server crashes to report. Job well done. {On server, counting crashed self, 2 on server is i3/i7 me and me}
----------------------

===========================================================
i3=800x600, windowed, standing at spawn location: i3-3225-8GB GTX560-1GB W10-1607 2017-02-Drivers, DX-June-2010 GTAV-1.36-NewInstall RMP 0.1.0.3 = trying to run 24/7
-----------------------------------------------------------
001: 170210-08:08pm Client Started, spawned normally, packages loaded
001: 170210-08:16pm Maximized, Client Close No message [Uptime: 8 minutes] {2 on server}
003: 170210-08:17pm Client Started, Client failed to load packages, RAGEMP: Can't Join Server, Exited Client.
004: 170210-08:20pm Client Started, spawned normally, packages loaded
004: 170210-10:22pm Maximized, Client Close, No message, Client Idle at spawn since spawn. (Note: Closed at exact same time as other machine joined the server) [Uptime: 2 hours 2 minutes] {2 on server}
006: 170210-10:24pm Client Started, spawned normally, packages loaded
006: 170211-12:39am Maximized, Client Close, No message, Client Idle at spawn since spawn. [Uptime: 2 hours 15 minutes] {5 on server}
008: 170211-12:41am Client Started, spawned normally, packages loaded
008: 170211-12:30pm Minimized, Client Close, No message, Client Idle at spawn since spawn. Closed while sleeping Perhaps ran 6 hours more. [Uptime: 11 hours 49 minutes+] {12 on server}
010: 170211-06:59pm Client Started, spawned normally, packages loaded

===========================================================
i7=800x600, windowed, standing at spawn location: i7-4790-8GB GTX760-2GB W10-1607 2017-01-Drivers, DX-June-2010 GTAV-1.36-NewInstall RMP 0.1.0.3 = trying to run 24/7
-----------------------------------------------------------
002: 170210-08:13pm Client Started, spawned normally, packages loaded
002: 170210-09:30pm or later Minimized, Client Close, No message, didnt notice for 1 hour [Uptime: 1 hour 17 minutes] {2 on server}
005: 170210-10:22pm Client Started, spawned normally, packages loaded (Client join likley triggerd i3 client to close)
005: 170211-12:05am Maximized, Client Close, No message [Uptime: 1 hour 43 minutes] {4 on server}, Running Kaspersky virus scan and hard drive search, one minute after new player joined spawned car and drove away
007: 170211-12:08am Client Started, spawned normally, packages loaded
007: 170211-12:39am Maximized, Client Close, No message, [Known Closure cause.] Close as a result of Video Render start in Vegas 14, pre running process 52% cpu, 4.2 of 8.0 ram, GTA V SP does not close ever, ragemp closes everytime 3 seconds into render.
009: 170211-02:34am Client Started, spawned normally, packages loaded
009: 170211-12:30pm Minimized, Client Crashed with message "Grand Theft Auto V has stopped working [Close Program]", Client Idle at spawn since spawn. Closed while sleeping Perhaps ran 6 hours more. [Uptime: 9 hours 56 minutes+] {12 on server}
011: 170211-07:02pm Client Started, spawned normally, packages loaded

**Comment by ragemp** [comment]
That's already fixed in 0.2: #62.

**Comment by treboR-0** [comment]
Coool, but just in case you wanted more.... save this for a rainy day.
It is basically more of the same, most notable is 3 dual crashes, both
clients on separate computers crashing at exact same time, and several
crashes related to switching windows with alt+tab on the i3 only.


==
i3
--
010: 170211-07:19pm Maximized, Client Close, No message, Client Idle
at spawn since spawn. [Uptime: 20 minutes] {3 on server}
012: 170211-07:21pm Client Started, spawned normally, packages loaded
012: 170211-07:23pm Maximized, Client Close, No message, Client Idle
at spawn since spawn. Was adjusting window position of MTA Client at
same time. MTA Client always runs in 800x600 below RageMP Client,
RageMP client [Uptime: 2 minutes] {4 on server} [Crash Cause: MTA =
1], MTA Client [Uptime: 2 days+]
013: 170211-07:26pm Client Started, spawned normally, packages loaded
013: 170211-10:41pm Maximized, Client Close, No message, Client Idle
at spawn since spawn. Client Closed while Alt+Tab to switch to MTA
Client. [Uptime: 3 hours 15 minutes] {5 on server} [Crash Cause: MTA =
2]
014: 170211-10:43pm Client Started, spawned normally, packages loaded
014: 170212-12:04am Maximized, Client Close, No message, Client Idle
at spawn since spawn. Client Closed 15 seconds after Alt+Tab to switch
to MTA Client. [Uptime: 1 hour 21 minutes] {5 on server} [Crash Cause:
MTA = 3]
015: 170212-12:05am Client Started, spawned normally, packages loaded
015: 170212-01:05am Maximized, Client Froze while i was watching it,
player was in bored looking around mode, had not touched computer
since last open, Blue Circle spun for 30 seconds, Grand Theft Auto V
has stopped working [Close Program] Client was Idle at spawn since
spawn. [Uptime: 1 hour] {5 on server}
017: 170212-12:05am Client Started, spawned normally, packages loaded
017: 170212-03:07am Maximized, Client Froze while i was watching it,
had not touched computer since last close, Two people left just before
it crashes, !2nd double crash! my i7 crashed 5 seconds later. Grand
Theft Auto V has stopped working [Close Program] Client was Idle at
spawn since spawn. [Uptime: 3 hours 2 minutes] {21 on server - Server
dropped to 17 the returned to 22, likely multiple people crashed.}
018: 170212-03:09am Client Started, spawned normally, packages loaded
018: 170212-04:43am Maximized, Client Froze. Grand Theft Auto V has
stopped working [Close Program] !3rd double crash! (019). i7 crashed
at exact same time. possibly one other on server crashed. [Uptime: 1
hours 36 minutes] {8 on server}
020: 170212-04:45am Client Started, spawned normally, packages loaded
020: 170212-05:12am Maximized, Client Froze, had not touched computer
since last open. Grand Theft Auto V has stopped working [Close
Program] [Uptime: 27 minutes] {9 on server}
022: 170212-05:14am Client Started, spawned normally, packages loaded
022: 170212-08:23pm Maximized, Client Close, No message, Client Idle
at spawn since spawn. [Uptime: 3 hours 9 minutes] {10 on server}
024: 170212-08:25am Client Started, spawned normally, packages loaded

==
i7
--
011: 170211-09:49pm Maximized, Client Close, No message, [Known
Closure cause. (2nd time)] Close as a result of Video Render start in
Vegas 14, GTA V SP does not close ever, RageMP closes everytime 3
seconds into video render.
015: 170211-10:55pm Client Started, spawned normally, packages loaded
015: 170211-11:30pm Maximized, Client Close, No message. Exact close
time not noticed. [Uptime: 35 minutes] {5 on server}
016: 170211-11:55pm Client Started, spawned normally, packages loaded
016: 170212-01:43am Maximized, Client Froze, Screen looked active but
notihng moved, Client didnt turn white, No message. Closed program, no
crash. [Uptime: 1 hour 48 minutes] {8 on server}
016: 170212-01:45am Client Started, spawned normally, packages loaded
016: 170212-03:07am Full Screen, Client Froze while i was watching it,
Two people left just before it crashes, !2nd double crash! my i3
crashed 5 seconds earlier. Grand Theft Auto V has stopped working
[Close Program] Client was Idle at spawn since spawn. [Uptime: 1 hour
22 minutes] {21 on server - Server dropped to 17 the returned to 22,
likely multiple people crashed.}
019: 170212-03:11am Client Started, spawned normally, packages loaded
019: 170212-04:43am Full Screen, Client Froze. Grand Theft Auto V has
stopped working [Close Program] !3rd double crash! (018). i3 crashed
at exact same time. possibly one other on server crashed. [Uptime: 1
hours 34 minutes] {8 on server}
021: 170212-04:47am Client Started, spawned normally, packages loaded
021: 170212-05:19am Full Screen, Client Froze. Riding in cop car,
encountered map object. Grand Theft Auto V has stopped working [Close
Program] [Uptime: 29 minutes] {7 on server}
023: 170212-05:21am Client Started, spawned normally, packages loaded

Hype for 0.2.1 :-D
