### ISSUE TITLE
Client-side events

### ISSUE THREAD

**Issue by n-n1ks** [ragemultiplayer/issues-archived#126]
**Browser events:**
- [x] browserCreated => (browser)
- [x] browserDomReady => (browser)
- [x] browserLoadingFailed => (browser)

**Colshape events:**

- [ ] colshapeHit => (colshape, entity, matchingDimension (boolean value: true - if entity dimension == colshape dimension, else - false)
- [ ] colshapeLeave => (colshape, entity, matchingDimension (boolean value: true - if entity dimension == colshape dimension, else - false)

**Entity events:**

- [x] entityStreamIn => (entity)
- [x] entityStreamOut => (entity)

**Marker events:**

- [ ] markerHit => (marker, entity, matchingDimension (boolean value: true - if entity dimension == colshape dimension, else - false)
- [ ] markerLeave => (marker, entity, matchingDimension (boolean value: true - if entity dimension == colshape dimension,else - false)

**Ped events:**

- [ ] pedDamaged => (ped, attacker (who deal damage), weapon, bodyPart (integer or string), damage (count of damage)
- [ ] pedWasted => (ped)
- [x] pedWeaponFire => (ped, weapon, ammo, ammoInClip, Vector3 {x: hitX;y: hitY;z: hitZ}, hitEntity (true, if entity, else - false)

**Pickup events:**

- [ ] pickupHit => (pickup, entity, matchingDimension (boolean value: true - if entity dimension == colshape dimension, else - false)
- [ ] pickupLeave => (pickup, entity, matchingDimension (boolean value: true - if entity dimension == colshape dimension, else - false)

**Player events:**

- [x] playerJoin => (player)
- [x] playerQuit => (player)
- [x] playerWeaponFire => (player, eapon, ammo, ammoInClip, Vector3 {x: hitX;y: hitY;z: hitZ}, hitEntity (true, if entity, else - false, Vector3 {x: startX;y: startY,z: startZ})
- [ ] playerWeaponSwitch => (player, previousWeapon, currentWeapon)
- [ ] playerTarget => (player, entity) - This event is triggered whenever the local player targets an element.
- [ ] playerDamage => (player, attacker (who deal damage), weapon, bodyPart (integer or string), damage (count of damage)
- [x] playerSpawn => (player)
- [x] playerWasted => (player)
- [ ] playerVehicleEnter => (player, vehicle, seat)
- [ ] playerVehicleExit => (player, vehicle, seat)
- [ ] playerChangeNick => (player, oldNick, newNick)

**Vehicle events:**

- [ ] vehicleSpawn => (vehicle)
- [ ] vehicleEnter => (vehicle, player, seat)
- [ ] vehicleExit => (vehicle, player, seat)
- [ ] vehicleExplode => (vehicle)
- [ ] vehicleStartEnter => (vehicle, player, seat). If "return true" - cancel enter.
- [ ] vehicleStartExit => (vehicle, player, seat). If "return true" - cancel exit.
- [ ] vehicleTrailerAttach => (vehicle, trailer)
- [ ] vehicleTrailerDetach => (vehicle, trailer)

**Comment by jrdnp** [comment]
They should be server-side events too

**Comment by n-n1ks** [comment]
Not all needed.

**Comment by ragemp** [comment]
@TempletonPeck most of them are already available serverside (atleast most of really needed of them).

**Comment by Mcfloy** [comment]
Can we add interiors events too ?

- [ ] playerInteriorEnter => (interior (integer), player)
- [ ] playerInteriorExit => (interior (integer), player)

We can have interiors ID with the _Interior::getInteriorAtCoordsWithType_ function and the [interiors list](https://github.com/TheUnravelGhoul/RageMP-Helpful/blob/master/interiors_list.json)
