### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by ironheart2004** [ragemultiplayer/issues-archived#127]
when i run Luncher.exe as administrator it opens and it show me every thing settings servers 
it well right now
but when i enter any server it open the game then it says loading story mod not ragemp multiplayer
then it open the normal story mod
i have deleted scripthook v and trainer and scripthookv net and nativeui 
so what is the soultion please

**Comment by ironheart2004** [comment]
help help

**Comment by ironheart2004** [comment]
please help me

**Comment by treboR-0** [comment]
RageMp 0.1 (Current) Supports GTA V versions 1.36-1.37 Download https://rage.mp/forums/topic/186-client-and-serverfiles/
RageMp 0.2 (Soon™) Supports GTA V versions 1.36-1.39
...wait for RageMP v0.2 or Downgrade to 1.37 https://yadi.sk/d/DOUd1Ss63FoSqg or 1.36
