### ISSUE TITLE
Cleint Bug

### ISSUE THREAD

**Issue by ironheart2004** [ragemultiplayer/issues-archived#128]
when i run Luncher.exe as administrator it opens and it show me every thing settings servers
it well right now
but when i enter any server it open the game then it says loading story mod not ragemp multiplayer
then it open the normal story mod
i have deleted scripthook v and trainer and scripthookv net and nativeui
so what is the soultion please

**Comment by TheHydroX** [comment]
that sounds like me.
i will say you are not logged in @ SC or your game install wa failing
