### ISSUE TITLE
GTAV has been upgraded to full version 1.41.

### ISSUE THREAD

**Issue by Kang-Programming** [ragemultiplayer/issues-archived#136]
GTAV has been upgraded to full version 1.41.

I am currently unable to determine the 
'Can't determine your game version. Please verify your game cache.' 
Will be displayed.

I would appreciate your prompt resolution.

**Comment by Flakee** [comment]
downgrade to 1.40 or wait for the 1.41 support

**Comment by streetgt** [comment]
RAGE:MP now supports latest dlc 1.41.
@ragemp close.
