### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by Mohex** [ragemultiplayer/issues-archived#148]
When i Want To Join A Server 
this Message Appears : RAGEmp_V has Stopped Working 
Note : GTA V story is Working 100%

**Comment by Chamiigore** [comment]
me pasa el mismo error :( lograste solucionarlo ??

**Comment by Lexalauren** [comment]
Когда запускаю онлаин у меня выскакивает ошибка. Прекращена работа программы "Updater". А одиночка работает отлично. Помогите пожалуйста.
