### ISSUE TITLE
FPS Drop on laptops with E-GPU

### ISSUE THREAD

**Issue by Bindwin** [ragemultiplayer/issues-archived#21]
With Rage, my GTA can't have more than 15 fps and sometimes my 16Gb ram are 99% used and 50-60% cpu... In Single or online i have 45-50 fps, 40% ram and 30% cpu... That's my problem... George all ready been notified about that.

**Comment by Carbowix** [comment]
i dont have any FPS Drop to be honest with ya

**Comment by Bindwin** [comment]
OK...your comment was helpful...

**Comment by d3dx9** [comment]
@Bindwin Please give us full details:

- Which Version? (Social Club/Steam/1.36)
- Your Computer Specs (CPU, GPU, RAM)

**Comment by Bindwin** [comment]
I have a social club version.
Laptop Spec :
    - CPU : i7 2860qm
    - RAM : Corsair vengeance 16Gb
    - GPU : DIY eGPU with gtx 960 4Gb

**Comment by Bindwin** [comment]
Please don't tell me that's my eGPU who caused this problem because I play many games (lastest or not) include Gary's mod who use a lot CEF architectures... My eGPU is like a Desktop GPU and plugged in PCIE and recognised perfectly. I think the problem appears when it put the error at launch "...playgtav.exe", maybe something cause infinite loop and take 99% of my ram.

**Comment by Bindwin** [comment]
@d3dx9 you forgot me?

**Comment by d3dx9** [comment]
Actually I didn't, @ragemp regognized it already.
