### ISSUE TITLE
Launcher stopped working,when i choosed server

### ISSUE THREAD

**Issue by masyanolchik** [ragemultiplayer/issues-archived#25]
![image](https://cloud.githubusercontent.com/assets/24855622/21578539/ac0a0636-cf8c-11e6-8bae-1270c5f082dd.png)
Choosing path with game.different nickname and compatible mode doesn't help me.Good luck to fix it.

**Comment by d3dx9** [comment]
Hello @masyanolchik,

please include full specs about your rig (CPU, GPU and RAM) and include your OS.

**Comment by masyanolchik** [comment]
Windows 10 Pro (Ukrainian version)
Ram:Kingston HyperX 1866 Mhz
CPU:AMD A10 58000k
GPU:Radeon RX460 4GB
HDD: Seagate Baraccuda 250GB

**Comment by masyanolchik** [comment]
Guy with the same problem solved it by reinstalling Windows with English.I try that too,and'l write about it.

**Comment by HUNTERMASTRO24** [comment]
i have problem here http://i.imgur.com/JoaZYRO.png / http://i.imgur.com/oK1XTiF.png / http://i.imgur.com/Ld54lnb.png
