### ISSUE TITLE
Баги RAGE Multiplayer

### ISSUE THREAD

**Issue by hartority** [ragemultiplayer/issues-archived#29]
Баги лаунчера:
1) Возможность выделять тексты в лаунчере, пункты меню ("Home", "Servers", "Direct Connect"...) и т.д.
2) Снизу есть ссылки на ресурсы, но если их открыть, а потом закрыть то закроется и сам лаунчер.
3) Лаунчер долговато подгружает фоновую картинку.
4) Не работает сортировка серверов.
5) Возможность просматривать Source Code лаунчера.
6) Нельзя перемещать форму лаунчера...
7) У лаунчера нету иконки, точнее в папке лаунчера она есть но лаунчер её не использует.
8) Не скрыта html версия лаунчера (https://rage.mp/testing/launcher/index.html)
9) Если лаунчер не может запустить игру (например вы не были авторизованны в стиме) то он намертво зависает.

Баги игры:
1) Очень плохо закреплены ники (Вроде обещают фиксануть)
2) Постоянная ошибка при входе, ну как же без неё (PlayGTAV.exe).
3) Из чата нельзя выйти на Esc.
4) Чат видно в меню паузы.

**Comment by iFrez** [comment]
Баги лаунчера:
3 и 8. Тут нужно использовать кеширующий прокси CDN. Тогда и трафик на сервере меньше будет уходить, грузиться быстрее да и в целом стабильнее.
10. Нельзя изменить язык лаунчера. Он на английском хотя выбран в меню русский.
11. Социалклабавская версия лаунчера запускает версию от стим. В итоге оба крашатся. 

Баги игры:
5. Не всегда регистрирует смерть игрока, парой он остается живым с минимальным уровнем здоровья и не умирает если продолжать в него стрелять.
6. Игроки с плохим коннектом к серdеру бездвижно "скользят по земле". Иногда игрок спавнится в воздухе и там застревает.

**Comment by ragemp** [comment]
> 11. Социалклабавская версия лаунчера запускает версию от стим. В итоге оба крашатся.

Лаунчер автоматически находит Steam-версию и запускает ее.
