### ISSUE TITLE
Serverside streamer broke vehicle sync for unstreamer players

### ISSUE THREAD

**Issue by Pixelpusher93** [ragemultiplayer/issues-archived#44]
Currently the car health seems to be unsynced because I saw people driving around with my burning car wrack.

**Comment by ragemp** [comment]
Vehicle health sync is synced, but there is bug caused by serverside streamer.

**Comment by Pixelpusher93** [comment]
Is the invisible vehicle issue also caused by this bug?

**Comment by ragemp** [comment]
No, invisible vehicles are helicopters with unloaded model.
