### ISSUE TITLE
List problems

### ISSUE THREAD

**Issue by zKaspy** [ragemultiplayer/issues-archived#47]
1. It does not reset the result of missions(A friend of mine because of the passage of missions is another model)
2.Players fly in the air (We do not see a model airplane)
 

Make a smooth synchronization, pls

**Comment by zKaspy** [comment]
Correct the possibility of finding more players with the same nickname on the server (as in make SAMP)

**Comment by ragemp** [comment]
1. There are no missions in RAGE MP.
2. They are in helicopter, but its model is unloaded.

And yeah, it's smooth enough.

**Comment by zKaspy** [comment]
It does not reset the result of the single player missions
