### ISSUE TITLE
Client-side scripting

### ISSUE THREAD

**Issue by ragemp** [ragemultiplayer/issues-archived#5]
- [x] Embed V8 clientside
- [x] Bind static game functions
- [x] Bind dynamic game functions
- [x] Resource downloading

**Comment by danilvalov** [comment]
@ragemp 
How to send to the client-side ui-resources (html, css, js) from the server-side?
Or do we need to create a special version of the client for our server?

I think the best solution is sending of ui-package from the server to the client when we are connected to the server.
You can check hash summ of the ui-package if you don't want to send ui-package every time when the client connects to the server.

**Comment by ragemp** [comment]
@danilvalov 
You have to put your resources to /client_packages/ directory, but this funtion is disabled in current release and will be enabled in upcoming 0.2.

**Comment by danilvalov** [comment]
@ragemp 
Sounds good! Thank you very much!

**Comment by Dominik48** [comment]
@ragemp 
Good job! This really necessary!
