### ISSUE TITLE
Extend chat features

### ISSUE THREAD

**Issue by danilvalov** [ragemultiplayer/issues-archived#55]
- [ ] add bind `F6` to open and close chat field (like in SAMP)
- [ ] add scroll in chat by Page Up/Page Down buttons
- [ ] add example with changed text colors in chat
- [ ] add closing chat field by Esc
- [ ] add support of text selection in chat field
- [ ] add focus in chat field always when chat is opened
- [ ] close chat field when Main Menu (by Esc) is opened (for example, when we hide the window with game and open it again)
- [ ] add saving chat to chatlog file
- [ ] save message history in chat field (when we press to Up and Down keyboard buttons in the chat field we switch between sent messages)

**Comment by Prakkkmak** [comment]
Yeah I want it too !
