### ISSUE TITLE
Launcher Problem

### ISSUE THREAD

**Issue by MonkEller** [ragemultiplayer/issues-archived#56]
1 Скриншот - Запуск Лаунчера в корневой папке "Grand Theft Auto V" на диске [D].
2 Скриншот - Загрузка Лаунчера и проверка DDOS-ATACK 
3 Скриншот - После ожидания загрузки лаунчера, подходит подготовка лаунчера и ожидания подгрузки дополнительных действий.
4 Скриншот - Запуск сервера под названием RAGE-MP [France].
5 Скриншот - Вылет буквально через 2-3 секунды, с оконным режимом в GTA V, проверка процесса в Диспетчере Задач на GTA V.
[https://pp.vk.me/c637430/v637430847/2c3e4/iGoldH35vyg.jpg](url) [https://pp.vk.me/c637430/v637430847/2c3ee/gUnldXYq1B8.jpg](url)
[https://pp.vk.me/c637430/v637430847/2c420/JiDD5f0ipH8.jpg](url)
[https://pp.vk.me/c637430/v637430847/2c448/BtCjbAZQbEQ.jpg](url)
[https://pp.vk.me/c637430/v637430847/2c466/q1Th3q0CGKw.jpg](url)

**Comment by ragemp** [comment]
Клиент соответствует версии игры? Сама игра рабочая? Punto Switcher или Process Killer есть?

**Comment by MonkEller** [comment]
1. Версия в одиночной пишет что 1.36, MP скачал для версии 1.36 и hotfix3 1.36.
2. Игра рабочая, одиночная рабочая.
3. Нет и нет.

**Comment by danilvalov** [comment]
1. Какую версию GTA V вы используете: Steam, Social Club или пиратскую? Если пиратскую, то пробовали ли вы скачать и установить игру из другого места?
2. Подключается ли мультиплеер к другим серверам? В частности, к официальному тестовому серверу RageMP и локальному серверу, запущенному на это же компьютере?

**Comment by MonkEller** [comment]
1. Пиратская, пробывал скачивать другую игру из другого места.
2. Не подключается, к локальной, если это одиночная, то подключается.

**Comment by klonplay** [comment]
Та же самая проблема, одиночная игра работает на ура но при запуске любого сервера RAGE:MP на 2 секунды открывается GTAV после чего закрывается без всяких ошибок.
