### ISSUE TITLE
In-game multiplayer UI

### ISSUE THREAD

**Issue by ragemp** [ragemultiplayer/issues-archived#63]

**Comment by Soonz** [comment]
Why not both of them ?

**Comment by Pixelpusher93** [comment]
I vote for both

**Comment by inv0ke** [comment]
Launcher is better imo, but I do think a setting to toggle either one is a better decision

**Comment by code4funnn** [comment]
What about both of them? And launcher with command line params in silent mode?

**Comment by Carbowix** [comment]
Yes do both of them. Great idea.

**Comment by Stellasin** [comment]
Both would be nice. But getting into the original interface would be hard.

**Comment by Stellasin** [comment]
So once this is done Beta 0.2 will release?

**Comment by inv0ke** [comment]
@Stellasin possibly, if no more issues are created or anything halts the release. Just be patient

**Comment by Stellasin** [comment]
That's nice

**Comment by treboR-0** [comment]
0.2 HYPE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Stellasin** [comment]
Oh so no launcher now?

**Comment by Stellasin** [comment]
Ах теперь нет запуска?

**Comment by Alexey04** [comment]
Поскорее бы уже сделали это.

**Comment by Stellasin** [comment]
Это будет 3 месяца

**Comment by Shwiser** [comment]
Возможно в в начале апреля готово будет

**Comment by Stellasin** [comment]
Надеюсь, это не первоапрельская шутка

**Comment by Shwiser** [comment]
Не,не шучу

**Comment by Stellasin** [comment]
Ха-ха ок

**Comment by Stellasin** [comment]
Я не могу ждать

**Comment by Shwiser** [comment]
Да,я тоже устал

**Comment by Stellasin** [comment]
Это почти 4 месяца

**Comment by Shwiser** [comment]
4 месяца,нас травят,что якобы скоро выйдет,но нет,я уже устал жду из последних сил

**Comment by ragemp** [comment]
@Shwiser Никто не заставляет сидеть сложа руки и ждать якобы из последних сил. Занимайтесь своими делами. Мы, между прочим, не просто ждем обновление, а работаем над ним четыре месяца (хотя на самом деле с момента последнего обновления прошло три месяца, никак не четыре).

**Comment by Stellasin** [comment]
Я думаю, стоит подождать

**Comment by Stellasin** [comment]
любые обновления?

**Comment by Shwiser** [comment]
Всмысле?

**Comment by Stellasin** [comment]
Я имею в виду, есть ли прогресс

**Comment by Shwiser** [comment]
Там вроде идет ЗБТ

**Comment by Stellasin** [comment]
xaxa

**Comment by Stellasin** [comment]
Этот вопрос мертв или находится в стадии разработки?

**Comment by Shwiser** [comment]
Возможно,скопытился

**Comment by Stellasin** [comment]
какие-нибудь Новости?

**Comment by Shwiser** [comment]
Есть,там на 1 проект если угадаешь что там щас идет на фотке тебе дадут ключ на ЗБТ сервера

**Comment by Stellasin** [comment]
Я не могу ждать

**Comment by Shwiser** [comment]
Ты на пиратке гоняешь?

**Comment by Stellasin** [comment]
Я использую пиратскую версию, потому что мой друг только пиратствует

**Comment by Shwiser** [comment]
Я щас в Rage mp не играю(т.к купил лицуху)

**Comment by Stellasin** [comment]
Вы тоже раскрутились?

**Comment by Stellasin** [comment]
Парни, пожалуйста, ускорьте это

**Comment by Shwiser** [comment]
Короч,ща ссылку на скрин кину,где примерно сказан выходи 0.2b

**Comment by Shwiser** [comment]
https://discordapp.com/channels/275731444876312588/292745923593895936 там наверх немного пролистай и внимательно на скрины смотри

**Comment by Stellasin** [comment]
@Shwiser вы говорите по-английски? Я использую Google Translate

**Comment by Shwiser** [comment]
Да,говорю

**Comment by Stellasin** [comment]
Oh ok. I'm just waiting for this thing. When will it finish?

**Comment by Shwiser** [comment]
Me too,amigo!

**Comment by Stellasin** [comment]
Пожалуйста, сделайте это быстро ragemp

**Comment by Shwiser** [comment]
Согласен

**Comment by Mcfloy** [comment]
Isn't it done since a moment ?

**Comment by Stellasin** [comment]
@Mcfloy Nope. I've been waiting for months.

**Comment by Alexey04** [comment]
We all have been waiting for months. But it isn't only one item which need
to be maken. There are a lot of items, which need to be maken. And the team
has been working hard for month.
P.S. sorry for my bad English.


On 25 May 2017 09:35, "Stellasin" <notifications@github.com> wrote:

@Mcfloy <https://github.com/mcfloy> Nope. I've been waiting for months.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ragemultiplayer/issues/issues/63#issuecomment-303935201>,
or mute the thread

**Comment by Stellasin** [comment]
I think mod is dead

**Comment by Mcfloy** [comment]
It's not dead, don't worry
