### ISSUE TITLE
Launcher Problem [x2]

### ISSUE THREAD

**Issue by MonkEller** [ragemultiplayer/issues-archived#71]
!!!!!!!!НЕ ИГНОРЬТЕ!!!!!!!!!!!!!
1 Скриншот - Запуск Лаунчера в корневой папке "Grand Theft Auto V" на диске [D].
2 Скриншот - Загрузка Лаунчера и проверка DDOS-ATACK
3 Скриншот - После ожидания загрузки лаунчера, подходит подготовка лаунчера и ожидания подгрузки дополнительных действий.
4 Скриншот - Запуск сервера под названием RAGE-MP [France].
5 Скриншот - Вылет буквально через 2-3 секунды, с оконным режимом в GTA V, проверка процесса в Диспетчере Задач на GTA V.
https://pp.vk.me/c637430/v637430847/2c3e4/iGoldH35vyg.jpg https://pp.vk.me/c637430/v637430847/2c3ee/gUnldXYq1B8.jpg
https://pp.vk.me/c637430/v637430847/2c420/JiDD5f0ipH8.jpg
https://pp.vk.me/c637430/v637430847/2c448/BtCjbAZQbEQ.jpg
https://pp.vk.me/c637430/v637430847/2c466/q1Th3q0CGKw.jpg

**Comment by danilvalov** [comment]
Не стоит дублировать темы, это не поможет делу.
В [первой теме](https://github.com/ragemultiplayer/issues/issues/56) задал вам дополнительные вопросы.
Дальнейшее обсуждение вашей проблемы будет вестись там.
