### ISSUE TITLE
Вылет сервера 

### ISSUE THREAD

**Issue by modernBB** [ragemultiplayer/issues-archived#72]
Лог gdb

```
Gordon_Freeman:а
[N] 178.206.216.216:55667 has been disconnected.
[N] 185.23.165.141:32461 has been disconnected.

Thread 1 "server" received signal SIGSEGV, Segmentation fault.
0x000021044614a7b2 in ?? ()
(gdb) quit
A debugging session is active.

Inferior 1 [process 19332] will be killed.

Quit anyway? (y or n) y
```

так же вот скрины вылетов без gdb:
http://image.prntscr.com/image/bb0842670e5a4e66a5d9925555efd1e2.png
http://image.prntscr.com/image/bdc55af68f2444b996462fdb9d45d821.png

надеюсь они чем то помогут

**Comment by ragemp** [comment]
Они ничем не помогут. Более того, второй скрин говорит о ошибке в скрипте, а не в сервере.

**Comment by modernBB** [comment]
но все же серв крашится когда вызываешь destroy автомобиля но в нем кто то сидит, и насчет ошибок, сервер ведь не крашиться когда есть ошибки, но из дебагера видно что сервер упал после выхода игроков, надеюсь исправите так как проблема не только у меня, з.ы. серв почти дефолтный

**Comment by ragemp** [comment]
> серв крашится когда вызываешь destroy автомобиля но в нем кто то сидит

А вот это нам уже может помочь. Первый скрин или второй связан именно с этим?

**Comment by modernBB** [comment]
Ошибка всегда как на втором скрине, теперь я удаляю только автомобили в которых нету игроков и серв не крашится
