### ISSUE TITLE
Things that my community will need.

### ISSUE THREAD

**Issue by treboR-0** [ragemultiplayer/issues-archived#87]
Once rock solid performance of server and client are established. These would be very nice for my MTA community to see on your system:

https://wiki.multitheftauto.com/wiki/SetVehicleHandling
https://wiki.multitheftauto.com/wiki/CreateObject
https://wiki.multitheftauto.com/wiki/EngineSetModelLODDistance setObjectLOD
https://wiki.multitheftauto.com/wiki/SetCameraTarget

Good mod.

**Comment by danilvalov** [comment]
@treboR-0 
Have you looked [here](https://wiki.rage.mp/index.php?title=Client-side_functions)?
I see there the `CreateObject()` function and other.

**Comment by treboR-0** [comment]
wow, great wiki. thanks
